# Generated by Django 6.0.8 on 2026-09-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteModel",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("phone", models.CharField(db_index=True, max_length=16)),
                ("invite_digest", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issued", "issued"),
                            ("email_given", "email_given"),
                            ("consumed", "consumed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_digest", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("email_given_at", models.DateTimeField(blank=True, null=True)),
                ("email_expires_at", models.DateTimeField(blank=True, null=True)),
                ("account_id", models.UUIDField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "accounts_invite",
                "indexes": [
                    models.Index(fields=["phone", "issued_at", "id"], name="accounts_invite_latest_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ("issued", "email_given", "consumed"))),
                        name="invite_kind_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "issued"), _negated=True),
                            models.Q(
                                ("account_id__isnull", True),
                                ("consumed_at__isnull", True),
                                ("email__isnull", True),
                                ("email_digest__isnull", True),
                                ("email_expires_at__isnull", True),
                                ("email_given_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="invite_issued_has_no_progress",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "email_given"), _negated=True),
                            models.Q(
                                ("account_id__isnull", True),
                                ("consumed_at__isnull", True),
                                ("email__isnull", False),
                                ("email_digest__isnull", False),
                                ("email_expires_at__isnull", False),
                                ("email_given_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="invite_email_given_has_email_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "consumed"), _negated=True),
                            models.Q(
                                ("account_id__isnull", False),
                                ("consumed_at__isnull", False),
                                ("email__isnull", False),
                                ("email_digest__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="invite_consumed_has_account",
                    ),
                ],
            },
        ),
    ]
