# Generated by Django 6.0.8 on 2026-09-22 17:51

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

BOARD = 1


def seed_board_revision(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """The one row exists from the start, so every writer only ever adds one to it."""
    BoardRevisionModel = apps.get_model("shared", "BoardRevisionModel")
    BoardRevisionModel.objects.get_or_create(pk=BOARD, defaults={"revision": 0})


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardRevisionModel",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("revision", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "shared_board_revision",
            },
        ),
        migrations.CreateModel(
            name="RateLimitHitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("at", models.DateTimeField()),
            ],
            options={
                "db_table": "shared_rate_limit_hit",
                "indexes": [models.Index(fields=["key", "at"], name="rate_limit_key_at")],
            },
        ),
        migrations.RunPython(seed_board_revision, migrations.RunPython.noop),
    ]
