# Generated by Django 6.0.8 on 2026-09-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=12)),
                ("message", models.TextField()),
                ("about_phone", models.CharField(blank=True, max_length=20)),
                ("web_version", models.CharField(max_length=32)),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feedback_feedback",
                "ordering": ("at",),
            },
        ),
    ]
