# Generated by Django 6.0.8 on 2026-09-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("kind", models.CharField(max_length=16)),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="places.placemodel",
                    ),
                ),
            ],
            options={
                "db_table": "places_place",
            },
        ),
        migrations.CreateModel(
            name="PlaceAliasModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=80, unique=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="places.placemodel",
                    ),
                ),
            ],
            options={
                "db_table": "places_alias",
                "ordering": ("place_id", "position"),
            },
        ),
    ]
