# Generated by Django 6.0.8 on 2026-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceMessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account", models.CharField(max_length=15)),
                ("message_id", models.CharField(max_length=120)),
                ("chat_jid", models.CharField(max_length=60)),
                ("sender_phone", models.CharField(max_length=15)),
                ("sender_name", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField()),
                ("text", models.TextField()),
                ("received_at", models.DateTimeField()),
            ],
            options={
                "db_table": "importing_source_message",
                "indexes": [models.Index(fields=["received_at"], name="importing_msg_received_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "message_id"), name="one_row_per_account_message"
                    )
                ],
            },
        ),
    ]
