# Generated by Django 6.0.8 on 2026-09-24 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedSenderModel",
            fields=[
                ("phone", models.CharField(max_length=15, primary_key=True, serialize=False)),
                ("blocked_at", models.DateTimeField()),
            ],
            options={
                "db_table": "importing_blocked_sender",
            },
        ),
        migrations.CreateModel(
            name="CandidateModel",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("sender_phone", models.CharField(max_length=15)),
                ("sender_name", models.CharField(blank=True, max_length=120)),
                ("text_key", models.CharField(max_length=2000)),
                ("text", models.TextField()),
                ("group_label", models.CharField(max_length=60)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("sources", models.PositiveSmallIntegerField(default=1)),
                ("verdict", models.CharField(max_length=8)),
                ("ride_id", models.UUIDField(blank=True, null=True)),
                ("joined", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=20)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("judged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "importing_candidate",
                "indexes": [
                    models.Index(fields=["sender_phone", "first_seen_at"], name="importing_cand_sender_idx"),
                    models.Index(fields=["verdict", "first_seen_at"], name="importing_cand_verdict_idx"),
                    models.Index(fields=["ride_id"], name="importing_cand_ride_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="sourcemessagemodel",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="importing.candidatemodel",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcemessagemodel",
            index=models.Index(fields=["candidate", "sent_at"], name="importing_msg_candidate_idx"),
        ),
    ]
