# Generated by Django 6.0.8 on 2026-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importing", "0003_ninth_digit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemovalRequestModel",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=16)),
                ("requested_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("decision", models.CharField(default="pending", max_length=8)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "importing_removal_request",
                "indexes": [models.Index(fields=["decision", "requested_at"], name="importing_removal_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("decided_at__isnull", True), ("decision", "pending")),
                            models.Q(
                                ("decided_at__isnull", False), ("decision__in", ("approved", "refused"))
                            ),
                            _connector="OR",
                        ),
                        name="removal_decision_and_moment_agree",
                    )
                ],
            },
        ),
    ]
