# Generated by Django 6.0.8 on 2026-09-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchEntryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("namespace", models.CharField(max_length=40)),
                ("document_id", models.CharField(max_length=64)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "search_entry",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "document_id"), name="one_entry_per_document"
                    )
                ],
            },
        ),
    ]
