# Generated by Django 6.0.8 on 2026-09-22 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideModel",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("car_id", models.UUIDField()),
                ("car_model", models.CharField(max_length=60)),
                ("car_color", models.CharField(max_length=60)),
                ("car_plate", models.CharField(max_length=7)),
                ("departure_at", models.DateTimeField()),
                ("original_departure_at", models.DateTimeField()),
                ("seats_available", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("payment_methods", models.JSONField()),
                ("published_at", models.DateTimeField()),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rides_ride",
            },
        ),
        migrations.CreateModel(
            name="RideEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=16)),
                ("at", models.DateTimeField()),
                ("payload", models.JSONField()),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rides.ridemodel",
                    ),
                ),
            ],
            options={
                "db_table": "rides_event",
                "ordering": ("ride_id", "position"),
            },
        ),
        migrations.CreateModel(
            name="ContactRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("at", models.DateTimeField()),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_requests",
                        to="rides.ridemodel",
                    ),
                ),
            ],
            options={
                "db_table": "rides_contact_request",
            },
        ),
        migrations.CreateModel(
            name="StopModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("kind", models.CharField(max_length=8)),
                ("place_id", models.CharField(blank=True, max_length=64)),
                ("text", models.CharField(blank=True, max_length=60)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="rides.ridemodel",
                    ),
                ),
            ],
            options={
                "db_table": "rides_stop",
                "ordering": ("ride_id", "position"),
            },
        ),
        migrations.AddIndex(
            model_name="ridemodel",
            index=models.Index(fields=["cancelled_at", "departure_at"], name="rides_board"),
        ),
        migrations.AddConstraint(
            model_name="rideeventmodel",
            constraint=models.UniqueConstraint(fields=("ride", "position"), name="one_event_per_position"),
        ),
        migrations.AddConstraint(
            model_name="stopmodel",
            constraint=models.UniqueConstraint(fields=("ride", "position"), name="one_stop_per_position"),
        ),
    ]
