# Generated by Django 6.0.8 on 2026-09-24 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ridemodel",
            name="driver_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="ridemodel",
            name="driver_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="ridemodel",
            name="origin_group_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="ridemodel",
            name="origin_kind",
            field=models.CharField(default="published", max_length=12),
        ),
        migrations.AddField(
            model_name="ridemodel",
            name="origin_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridemodel",
            name="origin_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ridemodel",
            name="car_color",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="ridemodel",
            name="car_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ridemodel",
            name="car_model",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="ridemodel",
            name="car_plate",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="ridemodel",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ridemodel",
            index=models.Index(fields=["driver_phone", "departure_at"], name="rides_external_departure"),
        ),
    ]
