/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as MinhasCaronasRouteImport } from './routes/minhas-caronas'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as CaronasRideIdRouteImport } from './routes/caronas.$rideId'
import { Route as CaronasRideIdEditarRouteImport } from './routes/caronas.$rideId.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasCaronasRoute = MinhasCaronasRouteImport.update({
  id: '/minhas-caronas',
  path: '/minhas-caronas',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CaronasRideIdRoute = CaronasRideIdRouteImport.update({
  id: '/caronas/$rideId',
  path: '/caronas/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaronasRideIdEditarRoute = CaronasRideIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => CaronasRideIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/minhas-caronas': typeof MinhasCaronasRoute
  '/publicar': typeof PublicarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/caronas/$rideId': typeof CaronasRideIdRouteWithChildren
  '/caronas/$rideId/editar': typeof CaronasRideIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/minhas-caronas': typeof MinhasCaronasRoute
  '/publicar': typeof PublicarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/caronas/$rideId': typeof CaronasRideIdRouteWithChildren
  '/caronas/$rideId/editar': typeof CaronasRideIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/conta': typeof ContaRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/minhas-caronas': typeof MinhasCaronasRoute
  '/publicar': typeof PublicarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/caronas/$rideId': typeof CaronasRideIdRouteWithChildren
  '/caronas/$rideId/editar': typeof CaronasRideIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/conta'
    | '/diagnostics'
    | '/entrar'
    | '/esqueci-senha'
    | '/minhas-caronas'
    | '/publicar'
    | '/redefinir-senha'
    | '/caronas/$rideId'
    | '/caronas/$rideId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/conta'
    | '/diagnostics'
    | '/entrar'
    | '/esqueci-senha'
    | '/minhas-caronas'
    | '/publicar'
    | '/redefinir-senha'
    | '/caronas/$rideId'
    | '/caronas/$rideId/editar'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/conta'
    | '/diagnostics'
    | '/entrar'
    | '/esqueci-senha'
    | '/minhas-caronas'
    | '/publicar'
    | '/redefinir-senha'
    | '/caronas/$rideId'
    | '/caronas/$rideId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ContaRoute: typeof ContaRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MinhasCaronasRoute: typeof MinhasCaronasRoute
  PublicarRoute: typeof PublicarRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  CaronasRideIdRoute: typeof CaronasRideIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-caronas': {
      id: '/minhas-caronas'
      path: '/minhas-caronas'
      fullPath: '/minhas-caronas'
      preLoaderRoute: typeof MinhasCaronasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caronas/$rideId': {
      id: '/caronas/$rideId'
      path: '/caronas/$rideId'
      fullPath: '/caronas/$rideId'
      preLoaderRoute: typeof CaronasRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caronas/$rideId/editar': {
      id: '/caronas/$rideId/editar'
      path: '/editar'
      fullPath: '/caronas/$rideId/editar'
      preLoaderRoute: typeof CaronasRideIdEditarRouteImport
      parentRoute: typeof CaronasRideIdRoute
    }
  }
}

interface CaronasRideIdRouteChildren {
  CaronasRideIdEditarRoute: typeof CaronasRideIdEditarRoute
}

const CaronasRideIdRouteChildren: CaronasRideIdRouteChildren = {
  CaronasRideIdEditarRoute: CaronasRideIdEditarRoute,
}

const CaronasRideIdRouteWithChildren = CaronasRideIdRoute._addFileChildren(
  CaronasRideIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ContaRoute: ContaRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MinhasCaronasRoute: MinhasCaronasRoute,
  PublicarRoute: PublicarRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  CaronasRideIdRoute: CaronasRideIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
